#!/bin/bash

# Initialize score to 0
score=0

# number of questions answered
n=10 
#  number of  questions in the array
M=100

questions=(
  "Who painted the Mona Lisa?"
  "What is the capital of France?"
  "Who wrote 'Romeo and Juliet'?"
  "Which planet is known as the Red Planet?"
  "In which year did World War II end?"
  "What is the largest ocean on Earth?"
  "Who was the first man to walk on the moon?"
  "What is the largest mammal in the world?"
  "Which country is known as the Land of the Rising Sun?"
  "What is the currency of the United Kingdom?"
  "What is the tallest mountain in the world?"
  "Which element has the chemical symbol 'O'?"
  "Who discovered penicillin?"
  "What is the capital of Italy?"
  "Which continent is the Sahara Desert located on?"
  "What is the largest desert in the world?"
  "Who invented the telephone?"
  "What is the main ingredient in guacamole?"
  "In which country did the Olympic Games originate?"
  "Which river is the longest in the world?"
  "What is the largest country in the world by land area?"
  "Which is the smallest country in the world?"
  "Who is known as the Father of India?"
  "In which year did the Titanic sink?"
  "Which element has the atomic number 1?"
  "Which famous scientist developed the theory of relativity?"
  "What is the largest island in the world?"
  "Who was the first president of the United States?"
  "What is the capital of Japan?"
  "Which famous ship sank in 1912 after hitting an iceberg?"
  "What is the smallest planet in the solar system?"
  "What is the longest river in the United States?"
  "Which animal is known as the King of the Jungle?"
  "What is the most spoken language in the world?"
  "Which country is famous for its pyramids?"
  "What is the chemical symbol for gold?"
  "What is the currency of Japan?"
  "Which is the largest planet in our solar system?"
  "What year did the Berlin Wall fall?"
  "Which country has the most population?"
  "Who was the first woman to fly solo across the Atlantic Ocean?"
  "Which human organ is capable of regenerating itself?"
  "What is the hardest natural substance on Earth?"
  "Which is the longest mountain range in the world?"
  "Which planet is closest to the sun?"
  "Who wrote '1984'?"
  "What is the capital of Spain?"
  "Which animal is known for its ability to change colors?"
  "What is the largest continent?"
  "What does DNA stand for?"
  "What is the fastest land animal?"
  "What is the main ingredient in sushi?"
  "What is the smallest bone in the human body?"
  "Who discovered gravity?"
  "Which sea is the saltiest in the world?"
  "Which country invented pizza?"
  "What is the chemical formula for water?"
  "What is the capital of Germany?"
  "Who painted the Sistine Chapel ceiling?"
  "What is the symbol for the chemical element Iron?"
  "Which animal is the largest land mammal?"
  "Who invented the light bulb?"
  "What is the name of the longest river in South America?"
  "Which country is known as the land of maple syrup?"
  "What is the name of the world's largest coral reef?"
  "What is the square root of 64?"
  "Who is the famous detective created by Sir Arthur Conan Doyle?"
  "What is the hardest rock on Earth?"
  "What is the name of the largest hot desert in the world?"
  "What animal is the symbol of the World Wildlife Fund (WWF)?"
  "Which famous physicist developed the three laws of motion?"
  "Which ancient civilization built the pyramids?"
  "What is the most common blood type?"
  "Which fruit is known as the 'king of fruits'?"
  "What year did Christopher Columbus discover the Americas?"
  "Who wrote the play 'Macbeth'?"
  "What does the term 'volcano' refer to?"
  "What is the capital of Canada?"
  "Which element is most abundant in the Earth's crust?"
  "What is the chemical symbol for water?"
  "Which bird is the symbol of peace?"
  "What is the fastest fish in the world?"
  "What is the largest city in the world by population?"
  "Which country is famous for its Great Wall?"
  "Who was the first female prime minister of the United Kingdom?"
  "What is the capital of Australia?"
  "Which country is home to the Great Barrier Reef?"
  "What is the capital of Egypt?"
  "Who developed the theory of evolution?"
  "What is the name of the closest star to Earth after the Sun?"
  "Which animal can live both in water and on land?"
  "Who painted 'Starry Night'?"
  "What is the currency of the United States?"
  "What is the capital of India?"
  "What is the largest country in Africa?"
  "Which country is known for the Eiffel Tower?"
  "What is the most famous ancient wonder of the world?"
  "Who wrote 'The Odyssey'?"
  "What is the capital of Russia?"
  "What is the tallest waterfall in the world?"
  "Who invented the airplane?"
  "What is the capital of Brazil?"
  "Which country is famous for its tulips?"
  "Which tree produces acorns?"
  "Who painted the 'Girl with a Pearl Earring'?"
  "What is the capital of South Korea?"
  "Which instrument has black and white keys?"
  "Who discovered America in 1492?"
  "Which animal is the symbol of the World Wildlife Fund?"
  "What is the currency of China?"
  "Which city is known as the Big Apple?"
  "What is the tallest building in the world?"
  "Which is the longest river in Africa?"
  "What is the smallest planet in the solar system?"
)

# Declare an array of 100 general culture answers
answers=(
  "Leonardo da Vinci"
  "Paris"
  "William Shakespeare"
  "Mars"
  "1945"
  "Pacific Ocean"
  "Neil Armstrong"
  "Blue whale"
  "Japan"
  "Pound Sterling"
  "Mount Everest"
  "Oxygen"
  "Alexander Fleming"
  "Rome"
  "Africa"
  "Antarctic Desert"
  "Alexander Graham Bell"
  "Avocado"
  "Greece"
  "Nile River"
  "Russia"
  "Vatican City"
  "Mahatma Gandhi"
  "1912"
  "Hydrogen"
  "Albert Einstein"
  "Greenland"
  "George Washington"
  "Tokyo"
  "Titanic"
  "Mercury"
  "Missouri River"
  "Lion"
  "Mandarin Chinese"
  "Egypt"
  "Au"
  "Yen"
  "Jupiter"
  "1989"
  "China"
  "Amelia Earhart"
  "Liver"
  "Diamond"
  "The Andes"
  "Mercury"
  "George Orwell"
  "Madrid"
  "Chameleon"
  "Asia"
  "Deoxyribonucleic Acid"
  "Cheetah"
  "Rice"
  "Stapes"
  "Isaac Newton"
  "Dead Sea"
  "Italy"
  "H2O"
  "Berlin"
  "Michelangelo"
  "Fe"
  "African Elephant"
  "Thomas Edison"
  "Amazon River"
  "Canada"
  "Great Barrier Reef"
  "8"
  "Sherlock Holmes"
  "Diamond"
  "Sahara Desert"
  "Giant Panda"
  "Isaac Newton"
  "Ancient Egyptians"
  "O positive"
  "Durian"
  "1492"
  "William Shakespeare"
  "A mountain that erupts with lava, ash, and gases"
  "Ottawa"
  "Oxygen"
  "H2O"
  "Dove"
  "Black Marlin"
  "Tokyo"
  "China"
  "Margaret Thatcher"
  "Canberra"
  "Australia"
  "Cairo"
  "Charles Darwin"
  "Proxima Centauri"
  "Amphibian"
  "Vincent van Gogh"
  "US Dollar"
  "New Delhi"
  "Algeria"
  "France"
  "Great Pyramid of Giza"
  "Homer"
  "Moscow"
  "Angel Falls"
  "Wright Brothers"
  "Brasília"
  "Netherlands"
  "Oak tree"
  "Johannes Vermeer"
  "Seoul"
  "Piano"
  "Christopher Columbus"
  "Panda"
  "Renminbi (Yuan)"
  "New York City"
  "Burj Khalifa"
  "Nile River"
  "Mercury"
)


# Function to ask a question and check the answer
ask_question() {
    local question="$1"
    local correct_answer="$2"
    echo "$question"
    i=1
    b=0
    while [ $i -lt 4 -a $b -eq 0 ]
    do        
        read -p "Votre réponse: " user_answer
        # Compare user's answer (case insensitive)
        if [[ "$user_answer" == "$correct_answer" ]];
        then
            echo "It is correct!"
            score=$(($score+1))
            b=1
        else
            echo "Bad answer"
        fi
        i=$(($i+1))
    done
    if [ $b -eq 0 ]
    then        
        echo "La bonne réponse était $correct_answer."        
    fi
}

# Welcome message
echo "Welcome to the quiz!"
echo "We will ask you  $n questions. Try to give correct answers"
echo

# Loop through each question
j=0
while [ $j -lt $n ]
do
    echo "Your score is  $score"
    r=$(($RANDOM % $M))
    ask_question "${questions[$r]}" "${answers[$r]}"
    j=$(($j+1))
done

# Final score
echo "Your final score is $score among $n questions."
